# 04_repos.yml - repositories and excludes

    - name: Repositorios disponibles en {{ ansible_hostname }}
      shell: echo -e  "$(yum repolist enabled |sed 's/Red Hat/RedHat/g' |  grep -v 'updating' | grep -v 'repositor' | grep -v ':' | awk 'NR==1{print "<tr><th>" $1 "</th><th>" $2 "</th><th>" $3 "</th><th>" $4 "</th><th>" $5 "</th><th>"} NR>1{print "<tr><td>" $1 "</td><td>" $2 "</td><td>" $3 "</td><td>" $4  "</td><td>" $5  "</td><td>"  }')" || echo -e '<p style=color:red;>REVISAR_⚠️ ⚠️NO HAY REPOSITORIOS DISPONIBLES_REVISAR</p>'
      register: repos

    - name: release en satellite para {{ ansible_hostname }}
      shell: echo -e "$(subscription-manager release --show  || echo -e '<p style=color:red;>⚠️ ⚠️REVISAR_ NO HAY RELEASE ASIGNADO EN SATELLITE_REVISAR</p>' )"
      register: subscriptionrelease
      changed_when: false
      failed_when: false

