---
# Archivo con todas las variables utilizadas en el rol sgadprevio
 
# Variables relacionadas con los ficheros
fichero: /home/reexus/Acceda2/SGADprevio/rhel_previo_{{ ansible_hostname }}_{{ ansible_distribution_version }}_{{ ansible_date_time.date }}.html
fich1: /home/reexus/.tmp_kk.1.txt
fich2: /home/reexus/.tmp_kk.2.txt
fich3: /home/reexus/.tmp_kk.3.txt
app_config_path: /opt/wildfly-10.1.0.Final/standalone/configuration/
enrichment_file_path: /home/reexus/enriquece/paraenriquecerParchea.lst
patching_dates_script_path: /home/reexus/Acceda2/fechas_parcheado.py
logo_file_path: /home/reexus/LOGO_GOB_MTDFP_AEAD.png
csv_report_path: /home/reexus/Acceda2/SGADprevio/rhel_previo_{{ ansible_hostname }}_{{ ansible_distribution_version }}_{{ ansible_date_time.date }}.csv
email_header_template_path: /home/reexus/Cloudera/cabecera.html
report_archive_path: /home/reexus/Acceda2/SGADprevio/almacen/
 
# Variables relacionadas con la suscripcion
subscription_release: 8.10
 
# Variables de configuracion
ansible_user: reexus
ansible_group: reexus
ansible_file_mode: '0664'
 
# Variables adicionales registradas en el playbook

enriquece: ""
ansible_distribution_version: "8.10"
fechas_parcheado: ""
ansible_date_time.date: ""
versionfutura: ""
paquetes: ""
hayupdates: ""
cambiorelease: ""
setsubscriptionrelease: ""
kernelLast: ""
suggested: ""
exclu: ""
subscription: ""
diasultimoreinicio: ""
subscriptionrelease: ""
repos: ""
ulti: ""
histo: ""
rpminstalados: ""
rpmsegactualizables: ""
reclamo: ""
iproute: ""
route: ""
iprouteall: ""
nmcli: ""
iptableslist: ""
fichbond: ""
masterslave: ""
 

reporting_host: adgesasateinfc2
